### ISSUE TITLE
Git tag of version for Bower

### ISSUE THREAD

**Issue by treygriffith** [catmanjan/jquery-dragster#12]
Bower needs a git tag of the right version (currently 1.0.3) in order to work properly.

All you need to do is:

```
$ git tag v1.0.3
$ git push origin v1.0.3
```

Once you have, I'll move the bower registry to point at this repo. Thanks!

**Comment by catmanjan** [comment]
Let me know if it's all good!

**Comment by treygriffith** [comment]
All set, it's now registered to this repo. Thanks for the help!
