### ISSUE TITLE
dragster on document

### ISSUE THREAD

**Issue by clarkk** [catmanjan/jquery-dragster#5]
Yes, the ordinary HTML5 dragenter/dragleave is crap! :D

Therefore I want to use dragster both on the body/document and on the dropzones to add some more user interaction

When the user drag something into the browser window I want to show the dropzones and when the drag leaves the browser window I want to hide the dropzones

When the user drag something over a dropzone I want to add a class to the dropzone and I want to remove the class when the drag leaves the dropzone

But when adding dragster directly on the document and on the dropzones at the same time is not working very well. You can see it for yourself :) When the drag leaves a dropzone the drag on the document is reset/gone

http://jsfiddle.net/L7v2f96z/9/

**Comment by catmanjan** [comment]
That JsFiddle is blank for me, or is that what you're try to show?

**Comment by clarkk** [comment]
Try to drag a file into the window :)

**Comment by catmanjan** [comment]
Dragster takes away the granularity of the drag+drop events, but in this case the granularity is required, I'd recommend using a combination of dragster and regular events:

http://jsfiddle.net/nr9jhz4e/

**Comment by clarkk** [comment]
thanks <3

**Comment by catmanjan** [comment]
No problem!
